env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 'latest'
plugins:
  - vue
  - '@typescript-eslint'
rules:
  {
    'vue/singleline-html-element-content-newline': 'off',
    'vue/html-self-closing': 'off',
  }
